name: MemberDetails
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: slack_users
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: member_details
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
