name: Qdrant
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: transformed_slack_messages
    required: false
  - name: qd_host
    inputType: FreeText
    description: The db host
    defaultValue: qdrant
    required: true
  - name: qd_port
    inputType: FreeText
    description: The db port
    defaultValue: 6333
    required: true
  - name: qd_collection
    inputType: FreeText
    description: The db name
    defaultValue: test_db
    required: true
  - name: qd_api_key
    inputType: Secret
    description: ''
    defaultValue: qd_api_key
    required: true
  - name: qd_host
    inputType: FreeText
    description: ''
    defaultValue: https://9c7bf8e0-6c92-47a0-bd44-800a087fcc68.europe-west3-0.gcp.cloud.qdrant.io
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
