name: Slack Events API
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: hello-world-source
    required: true
  - name: SLACK_BOT_TOKEN
    inputType: Secret
    description: ''
    defaultValue: slack_bot_token
    required: false
  - name: slack_app_token
    inputType: Secret
    description: ''
    defaultValue: internal_slack_app_token
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
